/*
 * controlador.c
 *
 *  Created on: 22 abr 2026
 *      Author: tomyl
 */


/* Auto-generated by FSM Grapher */
#include <stdint.h>
#include <controlador.h>
#include <main.h>
#include <simulador.h>

uint8_t BI = 0;
static uint8_t sentido = 1;




void abrir_porton(void)
{
	M1 = 1;
	M2 = 0;
}

void cerrar_porton(void)
{
	M1 = 0;
	M2 = 1;
}

void detener_porton(void)
{
	M1 = 0;
	M2 = 0;
}

/* Process event and execute actions */
estado_controlador CONT_evento(estado_controlador current, evento_controlador event) {
    estado_controlador next = current;
    switch (current) {
            case ESTADO_CONT_CERRADO:
                if (event == EVENTO_CONT_BC && (BI == 0)) {
                    next = ESTADO_CONT_ABRIENDO;
                    break;
                }
                if (event == EVENTO_CONT_BC && (BI == 1)) {
                    next = ESTADO_CONT_CERRADO;
                    break;
                }
                break;
            case ESTADO_CONT_ABIERTO:
                if (event == EVENTO_CONT_BC && (BI == 0)) {
                    next = ESTADO_CONT_CERRANDO;
                    break;
                }
                if (event == EVENTO_CONT_BC && (BI == 1)) {
                    next = ESTADO_CONT_ABIERTO;
                    break;
                }
                break;
            case ESTADO_CONT_ABRIENDO:
                if (event == EVENTO_CONT_TICK && (BI == 1)) {
                    next = ESTADO_CONT_REPOSO_INT;
                    break;
                }
                if (event == EVENTO_CONT_TICK && (BI == 0 && FC1 == 0)) {
                    next = ESTADO_CONT_ABRIENDO;
                    break;
                }
                if (event == EVENTO_CONT_TICK && (FC1 == 1)) {
                    next = ESTADO_CONT_ABIERTO;
                    break;
                }
                break;
            case ESTADO_CONT_CERRANDO:
                if (event == EVENTO_CONT_TICK && (BI == 1)) {
                    next = ESTADO_CONT_REPOSO_INT;
                    break;
                }
                if (event == EVENTO_CONT_TICK && (BI == 0 && FC2 == 0)) {
                    next = ESTADO_CONT_CERRANDO;
                    break;
                }
                if (event == EVENTO_CONT_TICK && (FC2 == 1)) {
                    next = ESTADO_CONT_CERRADO;
                    break;
                }
                break;
            case ESTADO_CONT_REPOSO_INT:
                if (event == EVENTO_CONT_TICK && (BI==1)) {
                    next = ESTADO_CONT_REPOSO_INT;
                    break;
                }
                if (event == EVENTO_CONT_BC && (BI == 0 && sentido == 1)) {
                    next = ESTADO_CONT_CERRANDO;
                    break;
                }
                if (event == EVENTO_CONT_BC && (BI == 0 && sentido == 0)) {
                    next = ESTADO_CONT_ABRIENDO;
                    break;
                }
                break;
            default: break;
        }

    if (next != current) {
        switch (next) {
            case ESTADO_CONT_ABRIENDO:
                sentido = 0;
                abrir_porton();
                break;
            case ESTADO_CONT_CERRANDO:
                sentido = 1;
                cerrar_porton();
                break;
            case ESTADO_CONT_REPOSO_INT:
                detener_porton();
                break;
            case ESTADO_CONT_ABIERTO:
                detener_porton();
                break;
            case ESTADO_CONT_CERRADO:
                detener_porton();
                break;
            default: break;
        }
    }
    return next;
}

/* Initialize FSM */
estado_controlador CONT_iniciar(void) {
	estado_controlador initial = ESTADO_CONT_CERRADO;
    return initial;
}
