/*
 * controlador.c
 *
 *  Created on: 22 abr 2026
 *      Author: tomyl
 */


/* Auto-generated by FSM Grapher */
#include <stdint.h>
#include <controlador.h>
#include <main.h>
#include <simulador.h>

uint8_t BI = 0;
static uint8_t sentido = 1;




void abrir_porton(void)
{
	M1 = 1;
	M2 = 0;
}

void cerrar_porton(void)
{
	M1 = 0;
	M2 = 1;
}

void detener_porton(void)
{
	M1 = 0;
	M2 = 0;
}

/* Process event and execute actions */
estado_controlador SIM_evento(estado_controlador current, evento_controlador event) {
    estado_controlador next = current;
    switch (current) {
        case ESTADO_SIM_CERRADO:
            if (event == EVENTO_SIM_BOTON_M1 && (BI == 0)) {
                next = ESTADO_SIM_ABRIENDO;
                break;
            }
            if (event == EVENTO_SIM_BOTON_M1 && (BI == 1)) {
                next = ESTADO_SIM_CERRADO;
                break;
            }
            break;
        case ESTADO_SIM_ABIERTO:
            if (event == EVENTO_SIM_BOTON_M2 && (BI == 0)) {
                next = ESTADO_SIM_CERRANDO;
                break;
            }
            if (event == EVENTO_SIM_BOTON_M2 && (BI == 1)) {
                next = ESTADO_SIM_ABIERTO;
                break;
            }
            break;
        case ESTADO_SIM_ABRIENDO:
            if (event == EVENTO_SIM_TICK && (BI == 1)) {
                next = ESTADO_SIM_REPOSO_INT;
                break;
            }
            if (event == EVENTO_SIM_TICK && (BI == 0 && FC1 == 0)) {
                next = ESTADO_SIM_ABRIENDO;
                break;
            }
            if (event == EVENTO_SIM_TICK && (FC1 == 1)) {
                next = ESTADO_SIM_ABIERTO;
                break;
            }
            break;
        case ESTADO_SIM_CERRANDO:
            if (event == EVENTO_SIM_TICK && (BI == 1)) {
                next = ESTADO_SIM_REPOSO_INT;
                break;
            }
            if (event == EVENTO_SIM_TICK && (BI == 0 && FC2 == 0)) {
                next = ESTADO_SIM_CERRANDO;
                break;
            }
            if (event == EVENTO_SIM_TICK && (FC2 == 1)) {
                next = ESTADO_SIM_CERRADO;
                break;
            }
            break;
        case ESTADO_SIM_REPOSO_INT:
            if (event == EVENTO_SIM_TICK && (BI==1)) {
                next = ESTADO_SIM_REPOSO_INT;
                break;
            }
            if (event == EVENTO_SIM_TICK && (BI == 0 && sentido == 1)) {
                next = ESTADO_SIM_CERRANDO;
                break;
            }
            if (event == EVENTO_SIM_TICK && (BI == 0 && sentido == 0)) {
                next = ESTADO_SIM_ABRIENDO;
                break;
            }
            break;
        default: break;
    }

    if (next != current) {
        switch (next) {
            case ESTADO_SIM_ABRIENDO:
                sentido = 0;
                abrir_porton();
                break;
            case ESTADO_SIM_CERRANDO:
                sentido = 1;
                cerrar_porton();
                break;
            case ESTADO_SIM_REPOSO_INT:
                detener_porton();
                break;
            default: break;
        }
    }
    return next;
}

/* Initialize FSM */
estado_controlador SIM_iniciar(void) {
	estado_controlador initial = ESTADO_SIM_CERRADO;
    return initial;
}
